[project]
name = "ep2-control"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pymavlink>=2.4.49",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
